- name: Deploiement des logs
  hosts: all
  
  vars:
    elasticsearch_host: localhost:9200
    elasticsearch_user: user
    elasticsearch_password: change

  tasks:
 
  - name: Set hostname
      ansible.builtin.hostname:
      name: Alex

  - name: Télécharger .deb
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.11.2-amd64.deb
        dest: /tmp/
        user: root
        group: root
        mode: 0644

 - name: Installer .deb  
     ansible.builtin.apt:
       deb: /tmp/filebeat-8.11.2-amd64.deb

 - name: Service Filebeat Start
     ansible.builtin.service:
       name: filebeat
       state: started

 - name: déploiement du template filebeat
     ansible.builtin.template:
       src: /template/filebeat.yml
       dest: /etc/filebeat/
       owner: root
       group: root
       mode: 0644
     notify:
      - Restart filebeat

 - name: déploiement du fichier de conf system
     ansible.builtin.file:
       src: /file/system.yml
       dest: /etc/filebeat/modules.d/
       owner: root
       group: root
       mode: 0644
     notify:
     - Restart filebeat

handlers:
 - name: Restart filebeat
    ansible.builtin.service:
      name: filebeat
      state: restarted
