- name: Playbook Tomcat
  hosts: all
  tasks:
  - name: Installation Tomcat
    ansible.builtin.package: 
     name: tomcat9
     state: latest

  - name: Service Tomcat Start
    ansible.builtin.service:
     name: tomcat9
     state: started

  - name: Download Conf Tomcat 
    ansible.builtin.get_url: 
      url: https://tomcat.apache.org/tomcat-9.0-doc/appdev/sample/sample.war
      dest: /var/lib/tomcat9/webapps
      owner: tomcat
      group: tomcat
      mode: 0644
