- name: Playbook Survey
  hosts: all
  tasks:
  - name: Installation de packets
    ansible.builtin.package: 
      name : "{{ item }}"     
      state: latest
    loop: "{{ variable.split('\n') }}"
